ACCOUNT_FIELD_LIST = [
    'Account.IsNewAccountStart'
    ,'Account.ParentID'
    ,'Account.ParentNumber'
    ,'Account.Name'
    ,'Account.Number'
    ,'Account.CRMID'
    ,'Account.DefaultPaymentMethod'
    ,'Account.PaymentTerm'
    ,'Account.PaymentGateway'
    ,'Account.PONumber'
    ,'Account.Batch'
    ,'Account.BillCycleDay'
    ,'Account.BcdSettingOption'
    ,'Account.InvoiceDeliveryByEmail'
    ,'Account.InvoiceDeliveryByPrint'
    ,'Account.InvoiceTemplateID'
    ,'Account.AdditionalEmailAddresses'
    ,'Account.CommunicationProfileName'
    ,'Account.Currency'
    ,'Account.Status'
    ,'Account.SalesRep'
    ,'Account.CSR'
    ,'Account.Notes'
    ,'Account.TaxExemptStatus'
    ,'Account.TaxExemptCertificateID'
    ,'Account.TaxExemptCertificateType'
    ,'Account.TaxExemptIssuingJurisdiction'
    ,'Account.TaxExemptDescription'
    ,'Account.Nav_Account_Number__c'
    ,'Account.Legal_Entity__c'
    ,'Account.Migration_Note__c'
    ,'Account.VATId'
]



CONTACT_FIELD_LIST = [
    'Contact.IsNewContactStart'
    ,'Contact.IsBillTo'
    ,'Contact.IsSoldTo'
    ,'Contact.FirstName'
    ,'Contact.LastName'
    ,'Contact.NickName'
    ,'Contact.WorkEmail'
    ,'Contact.PersonalEmail'
    ,'Contact.WorkPhone'
    ,'Contact.MobilePhone'
    ,'Contact.HomePhone'
    ,'Contact.OtherPhone'
    ,'Contact.OtherPhoneType'
    ,'Contact.Fax'
    ,'Contact.Country'
    ,'Contact.Address1'
    ,'Contact.Address2'
    ,'Contact.City'
    ,'Contact.StateProvince'
    ,'Contact.PostalCode'
    ,'Contact.County'
    ,'Contact.TaxRegion'
    ,'Contact.Description'
    ,'Contact.SFDC_Id__c'
    ,'Contact.Migration_Note__c'
]

MANGLE_EMAIL_ADDRESSES = [
    'WorkEmail'
    ,'PersonalEmail'    
]
