SUBSCRIPTION_FIELD_LIST = [
    'OrderType'
    ,'Subscription.Name'
    ,'Subscription.AccountNumber'
    ,'Subscription.InvoiceOwnerNumber'
    ,'Subscription.TermType'
    ,'Subscription.InitialTerm'
    ,'Subscription.InitialTermPeriodType'
    ,'Subscription.RenewalTerm'
    ,'Subscription.AutoRenew'
    ,'Subscription.TermStartDate'
    ,'Subscription.SaveAsDraft'
    ,'Subscription.OpportunityCloseDate__QT'
    ,'Subscription.OpportunityName__QT'
    ,'Subscription.OpportunityId__c'
    ,'Subscription.ContractNumber__c'
    ,'Subscription.PO_Number__c'
    ,'Subscription.SFDC_AccountId__c'
    ,'ContractEffectiveDate'
    ,'CustomerAcceptanceDate'
    ,'Subscription.Notes'
    ,'Subscription.Line_of_Business_LOB__c'
    ,'Subscription.Ledger_Code__c'
    ,'Subscription.Description__c'
    ,'Subscription.Migration_Notes__c'
    ,'RatePlan.ProductName'
    ,'RatePlan.IsNewRatePlanBegin'
    ,'RatePlan.Name'
    ,'Charge.Name'
    ,'Charge.Description'
    ,'Charge.Quantity'
    ,'Charge.BillingPeriod'
    ,'Charge.SpecificBillingPeriod'
    # ,'Charge.DiscountAmount'
    # ,'Charge.DiscountPercentage'
    # ,'Charge.UpToPeriods'
    ,'Charge.BillCycleType'
    ,'Charge.TriggerCondition'
    ,'Charge.TriggerDate'
    ,'Charge.RevenueRecognitionRuleName'
    ,'Charge.ChargeType'
    ,'Charge.Product_Family__c'
    ,'Charge.MigratedOpportunityLineItemId__c'
    ,'Charge.Line_Description__c'
    ,'Charge.Department__c'
    # ,'Tier.Tier'
    # ,'Tier.From'
    # ,'Tier.To'
    ,'Tier.Price'
    # ,'Tier.PriceFormat'
]